baseURL = "https://tomonobu3110.github.io/hugo_blog/"
languageCode = "ja-JP"
title = "Tomo3110's New Hugo Site"
publishDir = "docs"
theme = "pickles"
copyright = "Copyright; 2020, Tomonobu Saito. All rights reserved."

